// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stovia.proto

package stovia

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FutureValueRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Year                 string   `protobuf:"bytes,2,opt,name=year,proto3" json:"year,omitempty"`
	Quarter              string   `protobuf:"bytes,3,opt,name=quarter,proto3" json:"quarter,omitempty"`
	TargetYear           int32    `protobuf:"varint,4,opt,name=target_year,json=targetYear,proto3" json:"target_year,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FutureValueRequest) Reset()         { *m = FutureValueRequest{} }
func (m *FutureValueRequest) String() string { return proto.CompactTextString(m) }
func (*FutureValueRequest) ProtoMessage()    {}
func (*FutureValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d17da2f527e0106a, []int{0}
}

func (m *FutureValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FutureValueRequest.Unmarshal(m, b)
}
func (m *FutureValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FutureValueRequest.Marshal(b, m, deterministic)
}
func (m *FutureValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FutureValueRequest.Merge(m, src)
}
func (m *FutureValueRequest) XXX_Size() int {
	return xxx_messageInfo_FutureValueRequest.Size(m)
}
func (m *FutureValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FutureValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FutureValueRequest proto.InternalMessageInfo

func (m *FutureValueRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *FutureValueRequest) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *FutureValueRequest) GetQuarter() string {
	if m != nil {
		return m.Quarter
	}
	return ""
}

func (m *FutureValueRequest) GetTargetYear() int32 {
	if m != nil {
		return m.TargetYear
	}
	return 0
}

type FutureValueResponse struct {
	FutureValue          float64  `protobuf:"fixed64,1,opt,name=future_value,json=futureValue,proto3" json:"future_value,omitempty"`
	RecommendedToBuy     bool     `protobuf:"varint,2,opt,name=recommended_to_buy,json=recommendedToBuy,proto3" json:"recommended_to_buy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FutureValueResponse) Reset()         { *m = FutureValueResponse{} }
func (m *FutureValueResponse) String() string { return proto.CompactTextString(m) }
func (*FutureValueResponse) ProtoMessage()    {}
func (*FutureValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d17da2f527e0106a, []int{1}
}

func (m *FutureValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FutureValueResponse.Unmarshal(m, b)
}
func (m *FutureValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FutureValueResponse.Marshal(b, m, deterministic)
}
func (m *FutureValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FutureValueResponse.Merge(m, src)
}
func (m *FutureValueResponse) XXX_Size() int {
	return xxx_messageInfo_FutureValueResponse.Size(m)
}
func (m *FutureValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FutureValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FutureValueResponse proto.InternalMessageInfo

func (m *FutureValueResponse) GetFutureValue() float64 {
	if m != nil {
		return m.FutureValue
	}
	return 0
}

func (m *FutureValueResponse) GetRecommendedToBuy() bool {
	if m != nil {
		return m.RecommendedToBuy
	}
	return false
}

func init() {
	proto.RegisterType((*FutureValueRequest)(nil), "stovia.FutureValueRequest")
	proto.RegisterType((*FutureValueResponse)(nil), "stovia.FutureValueResponse")
}

func init() { proto.RegisterFile("stovia.proto", fileDescriptor_d17da2f527e0106a) }

var fileDescriptor_d17da2f527e0106a = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x4f, 0x03, 0x31,
	0x0c, 0x85, 0x39, 0x5a, 0x0a, 0xb8, 0x15, 0x42, 0x66, 0x89, 0xca, 0x40, 0xb9, 0xa9, 0x03, 0xea,
	0x00, 0xbf, 0x00, 0x06, 0x18, 0xd8, 0x22, 0x84, 0xc4, 0x14, 0xa5, 0x3d, 0x1f, 0xaa, 0x44, 0xeb,
	0xab, 0xe3, 0x14, 0xdd, 0xbf, 0x47, 0x97, 0x80, 0x28, 0xa2, 0x9b, 0xfd, 0xbd, 0x44, 0xef, 0xf9,
	0xc1, 0x28, 0x28, 0x6f, 0x97, 0x7e, 0xd6, 0x08, 0x2b, 0xe3, 0x20, 0x6f, 0xe5, 0x27, 0xe0, 0x63,
	0xd4, 0x28, 0xf4, 0xea, 0x3f, 0x22, 0x59, 0xda, 0x44, 0x0a, 0x8a, 0x08, 0xfd, 0x05, 0x57, 0x64,
	0x8a, 0x49, 0x31, 0x3d, 0xb5, 0x69, 0xee, 0x58, 0x4b, 0x5e, 0xcc, 0x61, 0x66, 0xdd, 0x8c, 0x06,
	0x8e, 0x37, 0xd1, 0x8b, 0x92, 0x98, 0x5e, 0xc2, 0x3f, 0x2b, 0x5e, 0xc1, 0x50, 0xbd, 0xbc, 0x93,
	0xba, 0xf4, 0xa9, 0x3f, 0x29, 0xa6, 0x47, 0x16, 0x32, 0x7a, 0x23, 0x2f, 0x65, 0x0d, 0x17, 0x7f,
	0x8c, 0x43, 0xc3, 0xeb, 0x40, 0x78, 0x0d, 0xa3, 0x3a, 0x61, 0xb7, 0xed, 0x78, 0x4a, 0x50, 0xd8,
	0x61, 0xfd, 0xfb, 0x14, 0x6f, 0x00, 0x85, 0x16, 0xbc, 0x5a, 0xd1, 0xba, 0xa2, 0xca, 0x29, 0xbb,
	0x79, 0x6c, 0x53, 0xac, 0x13, 0x7b, 0xbe, 0xa3, 0xbc, 0xf0, 0x43, 0x6c, 0x6f, 0x2d, 0xf4, 0xee,
	0x9b, 0x25, 0x3e, 0xc3, 0xd9, 0x13, 0xe9, 0x8e, 0x23, 0x8e, 0x67, 0xdf, 0x85, 0xfc, 0xbf, 0x7f,
	0x7c, 0xb9, 0x57, 0xcb, 0x11, 0xcb, 0x83, 0xf9, 0x20, 0x75, 0x78, 0xf7, 0x15, 0x00, 0x00, 0xff,
	0xff, 0xc1, 0x8e, 0x0c, 0xc5, 0x53, 0x01, 0x00, 0x00,
}
